version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  wordpress:
    depends_on:
      - db
    # image: wordpressImage # name specified during the build (if image is already built - by docker build)
    build:
      context: .
      dockerfile: Dockerfile # Use this when using docker-compose instead of docker build & run
    image: my-wordpress:6.4
    ports:
      - "8085:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_password # wordpress_password refers to the name of the secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    secrets:
      - wordpress_password
volumes:
  db_data:
secrets:
  wordpress_password:
    file: ./wordpress_password.txt
